### ISSUE TITLE
Package não carrega arquivos asset

### ISSUE THREAD

**Issue by guilhermehrcosta** [fireguard/report#1]
Olá, Ronaldo este package não carrega arquivos internos como javascript, css com o asset? Tem alguma maneira de fazer funcionar? Quando coloco asset ele dá timeout.

**Comment by meneguite** [comment]
Olá Guilherme.. carrega sim, mas precisa ter ciência que não usa o php para isso, assim o path para esses arquivos não podem ser relativos, pode usar a URL completa para o arquivo.. ou o que recomendo, gerar o path para o arquivo físico, assim evita uma chamada http e deixa o processo ainda mais rápido. Qualquer dúvida deixa aí que tento te ajudar.

**Comment by guilhermehrcosta** [comment]
Pode me passar um exemplo? Eu tenho um arquivo css na pasta public/css... Como posso gerar um path para o arquivo físico? Seria isto? Não né.

 <link rel="stylesheet" href="public/css/estilo.css" type="text/css"/>

**Comment by meneguite** [comment]
Usa o Laravel? Se sim, pode usar o helper dele assim: public_path('css/seu_arquivo.css');

**Comment by guilhermehrcosta** [comment]
Fiz deste jeito aqui no controle coloco isto : $estilo = public_path('css/estilo.css');
Passo esta variável no with da VIEW. Na view eu recupero essa variável com  
<link rel="stylesheet" href="{!!  $estilo  !!}" />

Isto mesmo? Está retornando erro no PhantomJS

**Comment by meneguite** [comment]
Pode usar o public_path direto na view.. mas assim deveria funcionar tb.. deixa um gist com parte do seu código para que eu possa dar uma olhada..

**Comment by guilhermehrcosta** [comment]
Controller: http://pastebin.com/Gtk6cTB8
View: http://pastebin.com/tdzSSkz7

**Comment by meneguite** [comment]
Guilherme pelo seu código não consegui identificar o erro, pode me passar qual o erro está gerando no Phantom?

**Comment by guilhermehrcosta** [comment]
PhantomJS: 1 0139AECE
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.

**Comment by meneguite** [comment]
Esse erro tem uma issue no repo do phanthomjs ( https://github.com/ariya/phantomjs/issues/14020 )mas me parece ser algo na instalação do Phantom.. tente remover o executável do Phantom que fica em vender/Bin e execute o composer install novamente para ele reinstalar o executável em sua aplicação.

**Comment by guilhermehrcosta** [comment]
Ok, você tem skype?

**Comment by meneguite** [comment]
Guilherme te adicionei lá.. conseguiu resolver o seu problema?

**Comment by guilhermehrcosta** [comment]
Não... Eu te chamei lá hoje, se não tiver como me dá um help hoje! Vamos continuar por lá.

**Comment by guilhermehrcosta** [comment]
Resolvido... O Artisan Server bloqueia conexões entradas, usando o PHP direto do Xammp o package funcionou 100%.
