### ISSUE TITLE
Erro Install Fireguard - /vendor/bin/phantomjs: not found

### ISSUE THREAD

**Issue by daniloras** [fireguard/report#10]
I have problem in install Fireguard.

Erro: 
` > PhantomInstaller\Installer::installPhantomJS
dashboard_1  | sh: /var/www/html/vendor/bin/phantomjs: not found
dashboard_1  | Script PhantomInstaller\Installer::installPhantomJS handling the post-install-cmd event terminated with an exception`

COMPOSER.JSON - scripts
`"post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
          ],
          "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
          ]`

COMPOSER.JSON - required
`"fireguard/report": "^0.1",
 "jakoch/phantomjs-installer": "2.1.1-p09",`

**Comment by meneguite** [comment]
Hello, for the description of the error it seems to me that it has not yet succeeded in installing the phantonjs executable. To what it describes I believe that it is enough to execute the "composer install" command so that it can download the executable in the correct folder (./vendor/bin/phantomjs).

**Comment by daniloras** [comment]
I am having trouble installing / phantomjs, but it does not install by composer install, where the above errors occur.

**Comment by ssiyamand** [comment]
i have this problem 
fireguard/report v0.1.8 requires jakoch/phantomjs-installer 2.1.1-p06 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p06] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.7 requires jakoch/phantomjs-installer 2.1.1-p06 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p06] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.6 requires jakoch/phantomjs-installer 2.1.1-p06 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p06] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.5 requires jakoch/phantomjs-installer 2.1.1-p06 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p06] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.4 requires jakoch/phantomjs-installer 2.1.1-p06 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p06] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.3 requires jakoch/phantomjs-installer 2.1.1-p06 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p06] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.2 requires jakoch/phantomjs-installer 2.1.1-p05 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p05] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.1 requires jakoch/phantomjs-installer 2.1.1-p05 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p05] but these conflict with you
r requirements or minimum-stability.
    - fireguard/report v0.1.0 requires jakoch/phantomjs-installer 2.1.1-p05 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p05] but these conflict with you
r requirements or minimum-stability.
    - Installation request for fireguard/report ^0.1 -> satisfiable by fireguard/report[v0.1.0, v0.1.1, v0.1.2, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.1.8]
