### ISSUE TITLE
Automatização da manipulação do header

### ISSUE THREAD

**Issue by lucasdearaujo** [fireguard/report#2]
Gostei da ideia da biblioteca, entretanto nessa primeira versão algo não ficou muito prático, que foi modo de realizar o output do relatório, conforme no exemplo do PDF.

Como cada exporter já é de uma natureza de arquivo pré-definida, o header pode ser encapsulado também, com as variações de **display** e **download**.

```php
$file = $exporter->setOrientation('landscape')
            ->setFormat('A3')
            ->setMargin('0px')
            ->generate($report);

$file->output(OutputMode::DISPLAY);
```

**Comment by meneguite** [comment]
Gostei muito da idéia.. talvez ao invés do generate poderíamos criar um response que já gera um output com uma resposta para http.. vou amadurecer essa idéia é em breve implemento isso.. se tiver interesse em enviar um pull request me dá um toque já alinhamos certinho..

**Comment by meneguite** [comment]
@lucasdearaujo a versão 0.1.6 agora implementa algo similar ao que sugeriu, novas sugestões serão sempre bem vindas. Qualquer dúvida deixa por aqui, que faço o possível para lhe ajudar!

**Comment by meneguite** [comment]
@lucasdearaujo qualquer dúvida entre em contato, por hora vou considerar como finalizada essa Issue. Obrigado pela sugestão!
