### ISSUE TITLE
Does not show Image in Header unless use same image in content.

### ISSUE THREAD

**Issue by arslansiddiq** [fireguard/report#3]
It does not show Image in Header unless i use same image in content then it shows both images in content and header. Can anyone tell me what is the problem
return $exporter
->setBinaryPath($binaryPath)
->setFormat('A3')
->response(new Report($html,$header,$footer))
->send();
It generates PDF

**Comment by meneguite** [comment]
Hello ... this is a limitation of the current Phantom version that can not work with asynchronous calls in the header and footer as you can see in the issue https://github.com/ariya/phantomjs/issues/14178. A possible solution is to use the images in base64, however to avoid a change in the code I will upload an update that looks for the header and footer images and includes them with display: none in content causing the call to be completed. Make sure the solution solves your problem and gives me feedback.
