### ISSUE TITLE
Table header

### ISSUE THREAD

**Issue by rafwell** [fireguard/report#4]
How i can repeat the table header on each new page?

**Comment by meneguite** [comment]
You can include a table with only the header in the header of the report.

**Comment by meneguite** [comment]
Or.. you can test this solution: http://stackoverflow.com/questions/12434790/table-heading-repeat-while-printing
But i not tested this.

**Comment by rafwell** [comment]
> You can include a table with only the header in the header of the report.

This not is a good ideia. We not have subreports in package. I have many tables in report.

> Or.. you can test this solution: http://stackoverflow.com/questions/12434790/table-heading-repeat-while-printing
But i not tested this.

This not work. Looks like not work in chrome engine.

**Comment by meneguite** [comment]
The table-header-group method should work, in previous version it worked correctly, I have identified that there is an issue already open in the phamtonjs repository with this same problem (https://github.com/ariya/phantomjs/issues/14691), unfortunately if put in the header is not an option for you, you should expect a correction for this problem in a new version of phantomjs that should not be long in coming.

**Comment by rafwell** [comment]
Thanx for reply. I'll follow the repository from now on.

**Comment by meneguite** [comment]
With the abandonment of the phantomjs project this issue will no longer be met, in the future if there is interest from the community we would have to carry this package to implement another render to export files.
