### ISSUE TITLE
Encoding problem when header+html+footer

### ISSUE THREAD

**Issue by rafwell** [fireguard/report#6]
Hi! When i have the html header + html + footer in same report the pdf not encode my report body properly. I need put an utf8_decode to work, but this is not a good idea.

`$html = utf8_decode(view()->make('admin.caixas.relatorios.fechamento', [
            'Caixa'=>$Caixa
        ])->render());

        $header = view()->make('admin.caixas.relatorios.header', [
            'Empresa'=>$Caixa->empresa
        ])->render();

        $footer = 
            '<style>  
                div{        
                    font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;    
                    font-size: 9px;
                    text-align: right;      
                    border-top: 1px #eeeeee solid; 
                    padding: 2px;
                }   
            </style>
            <div>
                Página <span>@{{ numPage }} de @{{ totalPages }}</span>
            </div>'; 

        $exporter = new \Fireguard\Report\Exporters\PdfExporter();
        
        return $exporter
            ->configure(['header' => ['height' => '70px']])
            ->response(new Report($html, $header, $footer))
            ->send();`

**Comment by meneguite** [comment]
Hi.. This problem should not happen, by default UTF8 is already used for html processing, make sure your php file is not in a different encode, in windows this happens frequently.

**Comment by rafwell** [comment]
The encoding of file it's okay. I'm using Ubuntu to dev.

Including <meta charset="utf-8" /> in head of html the encode of body of report its ok. But, if include header+body, the bug should appear

![image](https://cloud.githubusercontent.com/assets/2893078/21456785/c7f54eea-c911-11e6-8044-33c21376a77f.png)

**Comment by meneguite** [comment]
Well.. I'll try to simulate this problem here and I'll give you some feedback

**Comment by meneguite** [comment]
@rafwell include the **< meta  charset="UTF-8">**  in your body.. This will solve this problem.

**Comment by rafwell** [comment]
@meneguite the problem persists
